{{- if .Values.ngcApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: ngc-secret
  labels:
    {{- include "fraud-detection.labels" . | nindent 4 }}
type: Opaque
data:
  NGC_API_KEY: {{ .Values.ngcApiKey | b64enc | quote }}
{{- end }}
